# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: CI

on:
  push:
    branches: 
      - main
  workflow_dispatch: 

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
    - name: Show version
      run: "java -version"
    - name: Get repo
      uses: actions/checkout@v3
      with: 
        ref: jenk
        
    - name: Install dependencies
      run: "mvn compile"
      
    - name: Build with Maven
      run: "mvn -B package -DskipTests"

    - name: Test app
      run: "mvn test"
